# Generated by Django 3.2.20 on 2023-07-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField()),
                ('instructor', models.TextField()),
                ('desc', models.TextField()),
                ('video', models.FileField(upload_to='media/courses')),
                ('courseTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNo', models.IntegerField()),
                ('lessonName', models.TextField()),
                ('lessonDesc', models.TextField()),
                ('lessonTime', models.IntegerField()),
                ('video', models.FileField(upload_to='media/lessons')),
                ('chapterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteFile', models.FileField(upload_to='media/notes')),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.IntegerField()),
                ('chapterName', models.TextField()),
                ('chapterDesc', models.TextField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
