# Generated by Django 4.1.1 on 2023-07-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNo', models.IntegerField()),
                ('lessonName', models.TextField()),
                ('lessonDesc', models.TextField()),
                ('lessonTime', models.IntegerField()),
                ('video', models.FileField(upload_to='media/lessons')),
                ('chapterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteFile', models.FileField(upload_to='media/notes')),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
    ]
