# Generated by Django 3.2.20 on 2023-07-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField(null=True)),
                ('phN', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('father', models.CharField(max_length=100, null=True)),
                ('mother', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=30)),
                ('pinCode', models.IntegerField(null=True)),
                ('avatar', models.ImageField(null=True, upload_to='media/avatar')),
                ('myCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
