# Generated by Django 4.1.1 on 2023-07-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rightoption',
        ),
    ]
