# Generated by Django 4.1.1 on 2023-07-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_question_op1_remove_question_op2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qns',
            new_name='qnsText',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.TextField()),
                ('isCorrect', models.BooleanField()),
                ('qnsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
