# Generated by Django 4.1.1 on 2023-07-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_qns_question_qnstext_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='examId',
        ),
    ]
