# Generated by Django 4.1.1 on 2023-07-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_exam_question_examid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='owner',
        ),
    ]
