# Generated by Django 3.2.20 on 2023-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_timealloted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timeAlloted',
            field=models.TimeField(null=True),
        ),
    ]
