# Generated by Django 3.2.20 on 2023-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_question_timealloted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattended',
            name='optionId',
            field=models.IntegerField(null=True),
        ),
    ]
